In [1]:

#Python 3.8.4 64-bit

import numpy as np
import pandas as pd
import pandas_datareader.data as web
import datetime as datetime

In [2]:

dt_now = datetime.datetime.now()
ly = dt_now.year
lm = dt_now.month
ld = dt_now.day
print(ly, lm, ld)

2022 7 16


In [3]:
#codejp = input(int())
codejp = "1306"
stockcode = codejp+".JP"

In [4]:
import defmakevol

vodf = defmakevol.mdfmake(stockcode, 2009, 3)
vodf.head()

end


2009-03     2009-04    2009-05    2009-06    2009-07    2009-08  \
0  2309210.0   5243820.0  1931870.0  4795870.0  3893820.0  1905860.0   
1  2257470.0  10484930.0  3967670.0  3419100.0  3330380.0  2620610.0   
2  2554680.0   4143300.0  4787430.0  3878270.0  1915530.0  2188840.0   
3  1792160.0   2733290.0  5083320.0  3172980.0  1707220.0  1520690.0   
4  2623530.0   1998820.0  3033270.0  1373640.0  3050640.0  3131250.0   

     2009-09    2009-10    2009-11    2009-12  ...    2021-10    2021-11  \
0  2300800.0  1632000.0  2352720.0  3327240.0  ...  3879390.0  2351680.0   
1  1905120.0  5996540.0  1802080.0  2545910.0  ...  1844530.0  1375610.0   
2  1699410.0  3897580.0  1875490.0  3045910.0  ...  3916960.0  1299490.0   
3  1986080.0  2440780.0  1241210.0  2481390.0  ...  3564150.0  2478800.0   
4  1200410.0  2441740.0  1784790.0  4173770.0  ...  2854030.0  1082560.0   

     2021-12    2022-01    2022-02    2022-03    2022-04    2022-05  \
0  3795980.0  3075010.0  1329620.0  2022930.0  3411900.0  2017510.0   
1  3215070.0  1696000.0  2446340.0  2240740.0  1523570.0  2066480.0   
2  2410820.0  2591730.0   896390.0  1104400.0  1078710.0  2912510.0   
3  1427480.0  1673050.0  2086090.0  2682780.0  1310560.0  3485350.0   
4  1319900.0  1224970.0   785760.0  3871770.0  2500650.0  3687970.0   

     2022-06    2022-07  
0  1552810.0  3697750.0  
1   649850.0  2313180.0  
2  1553190.0  2048230.0  
3   944230.0  4054200.0  
4  1126760.0  1969180.0  

[5 rows x 161 columns]

In [5]:
import defmakedf

madedf = defmakedf.mdfmake(stockcode, 2009, 2)
madedf.head()

end


2009-02  2009-03  2009-04  2009-05  2009-06  2009-07  2009-08  2009-09  \
0    792.0    751.0    821.0    871.0    938.0    956.0    966.0    977.0   
1    790.0    744.0    851.0    910.0    942.0    951.0    969.0    957.0   
2    808.0    748.0    857.0    918.0    941.0    946.0    956.0    950.0   
3    802.0    758.0    856.0    926.0    938.0    938.0    966.0    942.0   
4    808.0    738.0    861.0    913.0    943.0    918.0    965.0    953.0   

   2009-10  2009-11  ...  2021-10  2021-11  2021-12  2022-01  2022-02  \
0    910.0    895.0  ...   2064.0   2126.0   2013.0   2122.0   1976.0   
1    891.0    894.0  ...   2055.0   2113.0   2003.0   2125.0   2015.0   
2    880.0    887.0  ...   2025.0   2136.0   2037.0   2082.0   2000.0   
3    883.0    888.0  ...   2018.0   2121.0   2025.0   2078.0   2012.0   
4    897.0    882.0  ...   2015.0   2119.0   2071.5   2072.0   2006.5   

   2022-03  2022-04  2022-05  2022-06  2022-07  
0   1977.5   2047.5   1998.0   2044.5   1946.5  
1   1938.5   2058.5   2017.5   2031.5   1974.0  
2   1958.5   2054.0   1978.0   2038.5   1983.5  
3   1920.5   2023.5   1964.0   2044.0   1959.5  
4   1869.0   1992.5   1950.5   2051.0   1940.0  

[5 rows x 162 columns]

In [6]:
#make next month return
mname = []
mnum = []
stmonth = []
nxrt1a = []
nxrt  =  []

# from 0 to 156   #200903-202204
for i in range(1,len(madedf.columns)-1):
  month = madedf.columns[i] + ">" + madedf.columns[i+1]
  startmonth = madedf.columns[i] 
  premonthdays = len(madedf[madedf.columns[i]].dropna())-1
  postmonthdays = len(madedf[madedf.columns[i+1]].dropna())-1
  prelastprice = madedf[madedf.columns[i]][premonthdays]
  postlastprice = madedf[madedf.columns[i+1]][postmonthdays]
  retans = (postlastprice/prelastprice)-1



  mname.append(month)
  mnum.append(i)
  stmonth.append(startmonth)
  nxrt.append(retans)
print('end')

end


In [7]:
nxrt1a = []
for i in range(0, len(madedf.columns)-2):
    premonthdays1a = len(madedf[madedf.columns[i]].dropna())-1
    postmonthdays1a = len(madedf[madedf.columns[i+1]].dropna())-1
    prelastprice1a = madedf[madedf.columns[i]][premonthdays1a]
    postlastprice1a = madedf[madedf.columns[i+1]][postmonthdays1a]
    retans1a = (postlastprice1a/prelastprice1a)-1
    nxrt1a.append(retans1a)
print("D")

D


In [8]:
import pandas as pd


returns = pd.DataFrame()
returns["mname"] = mname
returns["mnum"] = mnum
returns["nxrt1a"] = nxrt1a
returns["nxrt"] = nxrt
returns

mname  mnum    nxrt1a      nxrt
0    2009-03>2009-04     1  0.031048  0.086575
1    2009-04>2009-05     2  0.086575  0.064665
2    2009-05>2009-06     3  0.064665  0.036876
3    2009-06>2009-07     4  0.036876  0.000000
4    2009-07>2009-08     5  0.000000  0.018828
..               ...   ...       ...       ...
155  2022-02>2022-03   156 -0.003294  0.041688
156  2022-03>2022-04   157  0.041688 -0.023914
157  2022-04>2022-05   158 -0.023914  0.007500
158  2022-05>2022-06   159  0.007500 -0.020099
159  2022-06>2022-07   160 -0.020099 -0.012155

[160 rows x 4 columns]

In [9]:
import pandas as pd
mmnum  = pd.DataFrame()
mmnum["date"] = stmonth
mmnum["mnum"] = mnum
mmnum

date  mnum
0    2009-03     1
1    2009-04     2
2    2009-05     3
3    2009-06     4
4    2009-07     5
..       ...   ...
155  2022-02   156
156  2022-03   157
157  2022-04   158
158  2022-05   159
159  2022-06   160

[160 rows x 2 columns]

In [10]:
stmonth[0][5:7]

'03'

In [11]:
stmon = []

for i in stmonth:
    startmonth = i[0:4]+i[5:7]
    stmon.append(startmonth)
print("e")

e


In [12]:
dfname = []
for i in range(len(mnum)):
    #print(stmon[i])
    dfname.append("df"+stmon[i])
print(dfname)

['df200903', 'df200904', 'df200905', 'df200906', 'df200907', 'df200908', 'df200909', 'df200910', 'df200911', 'df200912', 'df201001', 'df201002', 'df201003', 'df201004', 'df201005', 'df201006', 'df201007', 'df201008', 'df201009', 'df201010', 'df201011', 'df201012', 'df201101', 'df201102', 'df201103', 'df201104', 'df201105', 'df201106', 'df201107', 'df201108', 'df201109', 'df201110', 'df201111', 'df201112', 'df201201', 'df201202', 'df201203', 'df201204', 'df201205', 'df201206', 'df201207', 'df201208', 'df201209', 'df201210', 'df201211', 'df201212', 'df201301', 'df201302', 'df201303', 'df201304', 'df201305', 'df201306', 'df201307', 'df201308', 'df201309', 'df201310', 'df201311', 'df201312', 'df201401', 'df201402', 'df201403', 'df201404', 'df201405', 'df201406', 'df201407', 'df201408', 'df201409', 'df201410', 'df201411', 'df201412', 'df201501', 'df201502', 'df201503', 'df201504', 'df201505', 'df201506', 'df201507', 'df201508', 'df201509', 'df201510', 'df201511', 'df201512', 'df201601', 'df

In [13]:

#pip install tqdm
madedf

2009-02  2009-03  2009-04  2009-05  2009-06  2009-07  2009-08  2009-09  \
0     792.0    751.0    821.0    871.0    938.0    956.0    966.0    977.0   
1     790.0    744.0    851.0    910.0    942.0    951.0    969.0    957.0   
2     808.0    748.0    857.0    918.0    941.0    946.0    956.0    950.0   
3     802.0    758.0    856.0    926.0    938.0    938.0    966.0    942.0   
4     808.0    738.0    861.0    913.0    943.0    918.0    965.0    953.0   
5     795.0    728.0    843.0    915.0    951.0    894.0    978.0    953.0   
6     795.0    718.0    868.0    888.0    944.0    882.0    982.0    947.0   
7     776.0    737.0    872.0    906.0    962.0    879.0    970.0    964.0   
8     779.0    719.0    878.0    885.0    968.0    860.0    977.0    958.0   
9     785.0    738.0    868.0    906.0    978.0    876.0    980.0    941.0   
10    774.0    758.0    860.0    911.0    973.0    874.0    957.0    941.0   
11    765.0    778.0    857.0    907.0    941.0    881.0    958.0    938.0   
12    768.0    781.0    875.0    900.0    949.0    887.0    954.0    948.0   
13    756.0    781.0    876.0    908.0    938.0    909.0    967.0    947.0   
14    750.0    810.0    855.0    909.0    942.0    915.0    954.0    957.0   
15    746.0    830.0    856.0    919.0    950.0    915.0    975.0    938.0   
16    763.0    834.0    862.0    922.0    926.0    927.0    975.0    918.0   
17    758.0    855.0    858.0    922.0    928.0    935.0    986.0    918.0   
18    773.0    852.0    855.0      NaN    946.0    936.0    973.0    921.0   
19      NaN    812.0    839.0      NaN    953.0    937.0    977.0      NaN   
20      NaN    797.0    866.0      NaN    942.0    943.0    974.0      NaN   
21      NaN      NaN      NaN      NaN    956.0    956.0      NaN      NaN   
22      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

    2009-10  2009-11  ...  2021-10  2021-11  2021-12  2022-01  2022-02  \
0     910.0    895.0  ...   2064.0   2126.0   2013.0   2122.0   1976.0   
1     891.0    894.0  ...   2055.0   2113.0   2003.0   2125.0   2015.0   
2     880.0    887.0  ...   2025.0   2136.0   2037.0   2082.0   2000.0   
3     883.0    888.0  ...   2018.0   2121.0   2025.0   2078.0   2012.0   
4     897.0    882.0  ...   2015.0   2119.0   2071.5   2072.0   2006.5   
5     902.0    886.0  ...   2041.0   2102.0   2083.5   2102.5   2017.5   
6     911.0    884.0  ...   2078.0   2087.0   2069.5   2088.0   2033.5   
7     915.0    879.0  ...   2060.0   2095.0   2053.5   2060.5   2045.0   
8     905.0    882.0  ...   2051.0   2124.0   2056.5   2069.5   2011.0   
9     922.0    875.0  ...   2066.0   2131.0   2052.0   2061.0   1993.0   
10    916.0    869.0  ...   2103.0   2134.0   2061.5   2000.0   2027.0   
11    920.0    862.0  ...   2101.0   2120.0   2094.0   2019.0   2010.0   
12    928.0    853.0  ...   2106.0   2115.0   2064.5   2005.0   2003.5   
13    928.0    854.0  ...   2109.0   2126.0   2019.0   2008.0   1990.5   
14    924.0    843.0  ...   2079.0   2126.0   2051.0   1973.5   1962.0   
15    915.0    846.0  ...   2082.0   2098.0   2049.0   1968.0   1934.5   
16    924.0    843.0  ...   2076.0   2107.0   2068.5   1917.0   1957.0   
17    910.0    825.0  ...   2098.0   2066.0   2067.0   1956.0   1967.0   
18    902.0    855.0  ...   2093.0   2028.5   2056.5   1973.5      NaN   
19    896.0      NaN  ...   2079.0   2008.0   2084.0      NaN      NaN   
20    908.0      NaN  ...   2082.0      NaN   2082.0      NaN      NaN   
21      NaN      NaN  ...      NaN      NaN   2073.5      NaN      NaN   
22      NaN      NaN  ...      NaN      NaN      NaN      NaN      NaN   

    2022-03  2022-04  2022-05  2022-06  2022-07  
0    1977.5   2047.5   1998.0   2044.5   1946.5  
1    1938.5   2058.5   2017.5   2031.5   1974.0  
2    1958.5   2054.0   1978.0   2038.5   1983.5  
3    1920.5   2023.5   1964.0   2044.0   1959.5  
4    1869.0   1992.5   1950.5   2051.0   1940.0  
5    1835.0   1996.0   1930.0   2076.5   1946.5  
6   

In [85]:
mnths = ["m"+str(i) for i in range(1,14)]
mnths = mnths[::-1]

In [86]:
import pandas as pd
import numpy as np

from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
from tqdm import tqdm

monStock = madedf.drop(columns=["2009-02"]) ##change from dfname

listm = monStock.columns


starti = 12

premonthcount = len(madedf.columns)-1

pbar = tqdm(premonthcount)
dflist = []
while starti < premonthcount-1:

    idtwcalc = []
    for p  in range(starti-12, starti+1):
        datap = monStock[monStock.columns[p]]
        datap = datap/monStock[monStock.columns[p]][0]
        datap = datap.dropna()
        t = monStock[monStock.columns[starti]]
        t = t/monStock[monStock.columns[starti]][0]
        t = t.dropna()

        dtw_distance, warp_path = fastdtw(datap, t, dist=euclidean)
        idtw = dtw_distance

        idtwcalc.append(idtw)


    idtwcalc = np.array(idtwcalc)
    idtwcalcres0  = idtwcalc.reshape(1,13) # decline var


    exec("df"+str(stmon[starti]) +"= pd.DataFrame(data = idtwcalcres0, index=[monStock.columns[starti]], columns = mnths)")
    exec("dfname" +"= df"+str(stmon[starti]))
    dflist.append(dfname)
  



    starti += 1
    pbar.update(1)
pbar.close()

print('end')

148it [00:15,  9.71it/s]

end


In [87]:
dflist[0]

m13       m12       m11       m10       m9        m8        m7  \
2010-03  0.443209  0.353447  0.317458  0.680249  1.86303  0.674931  1.530319   

               m6        m5        m4        m3        m2   m1  
2010-03  0.810527  1.482205  0.225204  0.519181  0.768632  0.0

In [88]:
cdf = pd.concat(dflist[i] for i in range(len(dflist)))

In [89]:
cdf

m13       m12       m11       m10        m9        m8        m7  \
2010-03  0.443209  0.353447  0.317458  0.680249  1.863030  0.674931  1.530319   
2010-04  0.918323  0.745543  0.182796  0.815944  0.118539  0.526895  0.218296   
2010-05  1.650244  1.070697  0.545050  0.956087  0.268129  0.925332  0.151589   
2010-06  0.385691  0.716604  0.291462  0.391745  0.167581  0.348093  0.816106   
2010-07  0.749224  0.146087  0.551910  0.264711  0.605840  0.682287  0.268536   
...           ...       ...       ...       ...       ...       ...       ...   
2022-02  0.565844  0.383849  0.243505  0.181461  0.166375  0.295852  0.237930   
2022-03  0.457472  0.724819  0.462461  0.716910  0.715848  0.485376  0.592831   
2022-04  0.146949  0.190983  0.566856  0.110765  0.262959  1.298769  0.457190   
2022-05  0.087707  0.220569  0.286522  0.106246  0.915725  0.119931  0.240757   
2022-06  0.594112  0.145446  0.310981  1.345879  0.742260  0.240968  0.899429   

               m6        m5        m4        m3        m2   m1  
2010-03  0.810527  1.482205  0.225204  0.519181  0.768632  0.0  
2010-04  0.525424  0.810161  0.399671  0.131717  0.877243  0.0  
2010-05  1.743241  1.289839  0.926124  1.816102  0.844143  0.0  
2010-06  0.372476  0.262749  0.874374  0.268089  0.561524  0.0  
2010-07  0.175260  0.704006  0.178876  0.897924  0.338838  0.0  
...           ...       ...       ...       ...       ...  ...  
2022-02  0.564402  0.226144  0.365683  0.287619  0.714691  0.0  
2022-03  0.503541  0.847774  0.598606  1.073927  0.832466  0.0  
2022-04  0.219035  0.894515  0.353745  0.341740  0.672078  0.0  
2022-05  0.486432  0.648340  0.218535  0.483821  0.242039  0.0  
2022-06  0.370444  0.361536  0.643945  0.167209  0.311137  0.0  

[148 rows x 13 columns]

ValueError: Length mismatch: Expected axis has 0 elements, new values have 13 elements

In [16]:
dflist[0].T.columns[0]

'2010-03'

In [17]:
edidf = df202204.T.sort_values("2022-04")
edidf = edidf.reset_index()
edidf["date"] = edidf["level_0"]

del edidf["level_0"]
edidf = pd.merge(edidf, mmnum, on="date")
edidf["m+1"] = edidf["mnum"]+1
edidf = pd.merge(edidf, returns, on="mnum")

edidf

2022-04     date  mnum  m+1            mname    nxrt1a      nxrt
0   0.000000  2022-04   158  159  2022-04>2022-05 -0.023914  0.007500
1   0.110765  2021-07   149  150  2021-07>2021-08 -0.038235  0.031600
2   0.146949  2021-04   146  147  2021-04>2021-05 -0.028752  0.012544
3   0.190983  2021-05   147  148  2021-05>2021-06  0.012544  0.010902
4   0.219035  2021-11   153  154  2021-11>2021-12 -0.035543  0.032620
5   0.262959  2021-08   150  151  2021-08>2021-09  0.031600  0.044960
6   0.341740  2022-02   156  157  2022-02>2022-03 -0.003294  0.041688
7   0.353745  2022-01   155  156  2022-01>2022-02 -0.048228 -0.003294
8   0.457190  2021-10   152  153  2021-10>2021-11 -0.015603 -0.035543
9   0.566856  2021-06   148  149  2021-06>2021-07  0.010902 -0.038235
10  0.672078  2022-03   157  158  2022-03>2022-04  0.041688 -0.023914
11  0.894515  2021-12   154  155  2021-12>2022-01  0.032620 -0.048228
12  1.298769  2021-09   151  152  2021-09>2021-10  0.044960 -0.015603

In [18]:
stmon[0]

'200903'

In [19]:
len(dflist)

148

In [20]:
dflist[0]

2009-03   2009-04   2009-05   2009-06  2009-07   2009-08   2009-09  \
2010-03  0.443209  0.353447  0.317458  0.680249  1.86303  0.674931  1.530319   

          2009-10   2009-11   2009-12   2010-01   2010-02 2010-03  
2010-03  0.810527  1.482205  0.225204  0.519181  0.768632     0.0

In [21]:
edidf

2022-04     date  mnum  m+1            mname    nxrt1a      nxrt
0   0.000000  2022-04   158  159  2022-04>2022-05 -0.023914  0.007500
1   0.110765  2021-07   149  150  2021-07>2021-08 -0.038235  0.031600
2   0.146949  2021-04   146  147  2021-04>2021-05 -0.028752  0.012544
3   0.190983  2021-05   147  148  2021-05>2021-06  0.012544  0.010902
4   0.219035  2021-11   153  154  2021-11>2021-12 -0.035543  0.032620
5   0.262959  2021-08   150  151  2021-08>2021-09  0.031600  0.044960
6   0.341740  2022-02   156  157  2022-02>2022-03 -0.003294  0.041688
7   0.353745  2022-01   155  156  2022-01>2022-02 -0.048228 -0.003294
8   0.457190  2021-10   152  153  2021-10>2021-11 -0.015603 -0.035543
9   0.566856  2021-06   148  149  2021-06>2021-07  0.010902 -0.038235
10  0.672078  2022-03   157  158  2022-03>2022-04  0.041688 -0.023914
11  0.894515  2021-12   154  155  2021-12>2022-01  0.032620 -0.048228
12  1.298769  2021-09   151  152  2021-09>2021-10  0.044960 -0.015603

In [22]:
returns

mname  mnum    nxrt1a      nxrt
0    2009-03>2009-04     1  0.031048  0.086575
1    2009-04>2009-05     2  0.086575  0.064665
2    2009-05>2009-06     3  0.064665  0.036876
3    2009-06>2009-07     4  0.036876  0.000000
4    2009-07>2009-08     5  0.000000  0.018828
..               ...   ...       ...       ...
155  2022-02>2022-03   156 -0.003294  0.041688
156  2022-03>2022-04   157  0.041688 -0.023914
157  2022-04>2022-05   158 -0.023914  0.007500
158  2022-05>2022-06   159  0.007500 -0.020099
159  2022-06>2022-07   160 -0.020099 -0.012155

[160 rows x 4 columns]

In [23]:
mmnum

date  mnum
0    2009-03     1
1    2009-04     2
2    2009-05     3
3    2009-06     4
4    2009-07     5
..       ...   ...
155  2022-02   156
156  2022-03   157
157  2022-04   158
158  2022-05   159
159  2022-06   160

[160 rows x 2 columns]

In [24]:
edidf = dflist[0].T

#edidf = edidf.sort_values(edidf.columns[0])
edidf = edidf.reset_index()
edidf["date"] = edidf["level_0"]
edidf = pd.merge(edidf, mmnum, on="date")
del edidf["level_0"]

edidf["m+1"] = edidf["mnum"]+1
edidf = pd.merge(edidf, returns, on="mnum")
edidf

2010-03     date  mnum  m+1            mname    nxrt1a      nxrt
0   0.443209  2009-03     1    2  2009-03>2009-04  0.031048  0.086575
1   0.353447  2009-04     2    3  2009-04>2009-05  0.086575  0.064665
2   0.317458  2009-05     3    4  2009-05>2009-06  0.064665  0.036876
3   0.680249  2009-06     4    5  2009-06>2009-07  0.036876  0.000000
4   1.863030  2009-07     5    6  2009-07>2009-08  0.000000  0.018828
5   0.674931  2009-08     6    7  2009-08>2009-09  0.018828 -0.054415
6   1.530319  2009-09     7    8  2009-09>2009-10 -0.054415 -0.014115
7   0.810527  2009-10     8    9  2009-10>2009-11 -0.014115 -0.058370
8   1.482205  2009-11     9   10  2009-11>2009-12 -0.058370  0.077193
9   0.225204  2009-12    10   11  2009-12>2010-01  0.077193 -0.005429
10  0.519181  2010-01    11   12  2010-01>2010-02 -0.005429 -0.008734
11  0.768632  2010-02    12   13  2010-02>2010-03 -0.008734  0.105727
12  0.000000  2010-03    13   14  2010-03>2010-04  0.105727  0.004980

In [25]:
dfedit = []
for i in range(len(dflist)):
    edidf = dflist[i].T
    edidf = edidf.sort_values(edidf.columns[0])
    edidf = edidf.reset_index()
    edidf["date"] = edidf["level_0"]

    del edidf["level_0"]
    edidf = pd.merge(edidf, mmnum, on="date")
    edidf["m+1"] = edidf["mnum"]+1
    edidf = pd.merge(edidf, returns, on="mnum")
    edidf["idtw"] = edidf[edidf.columns[0]]
    del edidf[edidf.columns[0]]
    
    dfedit.append(edidf)  

In [26]:
dfedit[0]

date  mnum  m+1            mname    nxrt1a      nxrt      idtw
0   2010-03    13   14  2010-03>2010-04  0.105727  0.004980  0.000000
1   2009-12    10   11  2009-12>2010-01  0.077193 -0.005429  0.225204
2   2009-05     3    4  2009-05>2009-06  0.064665  0.036876  0.317458
3   2009-04     2    3  2009-04>2009-05  0.086575  0.064665  0.353447
4   2009-03     1    2  2009-03>2009-04  0.031048  0.086575  0.443209
5   2010-01    11   12  2010-01>2010-02 -0.005429 -0.008734  0.519181
6   2009-08     6    7  2009-08>2009-09  0.018828 -0.054415  0.674931
7   2009-06     4    5  2009-06>2009-07  0.036876  0.000000  0.680249
8   2010-02    12   13  2010-02>2010-03 -0.008734  0.105727  0.768632
9   2009-10     8    9  2009-10>2009-11 -0.014115 -0.058370  0.810527
10  2009-11     9   10  2009-11>2009-12 -0.058370  0.077193  1.482205
11  2009-09     7    8  2009-09>2009-10 -0.054415 -0.014115  1.530319
12  2009-07     5    6  2009-07>2009-08  0.000000  0.018828  1.863030

In [27]:
Y = dfedit[0][0:1]["nxrt"]
X = dfedit[0][1:12]

In [28]:
import xgboost as xgb

In [29]:
df = dfedit

train = df[0:120]
valid = df[120:147]

In [30]:
dfd = df[0].drop(["date", "mname"], axis=1)
dfd

mnum  m+1    nxrt1a      nxrt      idtw
0     13   14  0.105727  0.004980  0.000000
1     10   11  0.077193 -0.005429  0.225204
2      3    4  0.064665  0.036876  0.317458
3      2    3  0.086575  0.064665  0.353447
4      1    2  0.031048  0.086575  0.443209
5     11   12 -0.005429 -0.008734  0.519181
6      6    7  0.018828 -0.054415  0.674931
7      4    5  0.036876  0.000000  0.680249
8     12   13 -0.008734  0.105727  0.768632
9      8    9 -0.014115 -0.058370  0.810527
10     9   10 -0.058370  0.077193  1.482205
11     7    8 -0.054415 -0.014115  1.530319
12     5    6  0.000000  0.018828  1.863030

In [31]:
train[0].columns[0]

'date'

In [32]:
df[len(dfedit)-1]

date  mnum  m+1            mname    nxrt1a      nxrt      idtw
0   2022-06   160  161  2022-06>2022-07 -0.020099 -0.012155  0.000000
1   2021-07   149  150  2021-07>2021-08 -0.038235  0.031600  0.145446
2   2022-04   158  159  2022-04>2022-05 -0.023914  0.007500  0.167209
3   2021-11   153  154  2021-11>2021-12 -0.035543  0.032620  0.240968
4   2021-08   150  151  2021-08>2021-09  0.031600  0.044960  0.310981
5   2022-05   159  160  2022-05>2022-06  0.007500 -0.020099  0.311137
6   2022-02   156  157  2022-02>2022-03 -0.003294  0.041688  0.361536
7   2022-01   155  156  2022-01>2022-02 -0.048228 -0.003294  0.370444
8   2021-06   148  149  2021-06>2021-07  0.010902 -0.038235  0.594112
9   2022-03   157  158  2022-03>2022-04  0.041688 -0.023914  0.643945
10  2021-10   152  153  2021-10>2021-11 -0.015603 -0.035543  0.742260
11  2021-12   154  155  2021-12>2022-01  0.032620 -0.048228  0.899429
12  2021-09   151  152  2021-09>2021-10  0.044960 -0.015603  1.345879

In [33]:
predlist = []

df = dfedit

for i in range(len(dfedit)-1):

    train = df[i][1:12]
    valid = df[i][0:1]
    
    #feat_cols = train.drop("date", "mname","nxrt")
    
    feat_cols = train.drop(columns=["date", "mname", "nxrt"]).columns.tolist()

    X_train = train[feat_cols]
    X_valid = valid[feat_cols]
    y_train = train["nxrt"]
    y_valid = valid['nxrt']

    import xgboost as xgb
    dtrain = xgb.DMatrix(X_train, y_train)
    dvalid = xgb.DMatrix(X_valid, y_valid)

    params = {
        "objective" : "reg:squarederror",
        "eval_metric" : "rmse"
    }

    model = xgb.train(
        params = params,
        dtrain = dtrain,
        evals = [(dtrain, "train"), (dvalid, "valid")],
        num_boost_round = 25
    )

    pred = model.predict(xgb.DMatrix(X_valid))
    predlist.append(pred)

print('end')

[0]	train-rmse:0.35151	valid-rmse:0.36327
[1]	train-rmse:0.25754	valid-rmse:0.26775
[2]	train-rmse:0.19038	valid-rmse:0.19850
[3]	train-rmse:0.14273	valid-rmse:0.18384
[4]	train-rmse:0.10833	valid-rmse:0.14383
[5]	train-rmse:0.08242	valid-rmse:0.13737
[6]	train-rmse:0.06297	valid-rmse:0.13187
[7]	train-rmse:0.04866	valid-rmse:0.12720
[8]	train-rmse:0.03838	valid-rmse:0.12323
[9]	train-rmse:0.03040	valid-rmse:0.11822
[10]	train-rmse:0.02420	valid-rmse:0.11445
[11]	train-rmse:0.01929	valid-rmse:0.11097
[12]	train-rmse:0.01542	valid-rmse:0.11046
[13]	train-rmse:0.01238	valid-rmse:0.10838
[14]	train-rmse:0.00994	valid-rmse:0.10719
[15]	train-rmse:0.00798	valid-rmse:0.10576
[16]	train-rmse:0.00646	valid-rmse:0.10515
[17]	train-rmse:0.00526	valid-rmse:0.10454
[18]	train-rmse:0.00431	valid-rmse:0.10410
[19]	train-rmse:0.00350	valid-rmse:0.10395
[20]	train-rmse:0.00286	valid-rmse:0.10356
[21]	train-rmse:0.00236	valid-rmse:0.10345
[22]	train-rmse:0.00198	valid-rmse:0.10324
[23]	train-rmse:0.001

In [34]:
predlist

[array([0.1081477], dtype=float32),
 array([0.04567565], dtype=float32),
 array([0.04561131], dtype=float32),
 array([-0.02423216], dtype=float32),
 array([0.10382248], dtype=float32),
 array([0.0636408], dtype=float32),
 array([-0.05384212], dtype=float32),
 array([-0.02066838], dtype=float32),
 array([0.00150503], dtype=float32),
 array([0.03552612], dtype=float32),
 array([-0.00399602], dtype=float32),
 array([0.01730919], dtype=float32),
 array([0.02054694], dtype=float32),
 array([0.08451235], dtype=float32),
 array([0.00720354], dtype=float32),
 array([-0.02636648], dtype=float32),
 array([0.04946465], dtype=float32),
 array([-0.03789445], dtype=float32),
 array([-0.00573259], dtype=float32),
 array([-0.01191367], dtype=float32),
 array([-0.00790504], dtype=float32),
 array([-0.06686706], dtype=float32),
 array([-0.01405016], dtype=float32),
 array([0.10767563], dtype=float32),
 array([0.10902806], dtype=float32),
 array([0.00971059], dtype=float32),
 array([-0.08263601], dtype=f

In [35]:


train_data = dflist[0:120]
train_data[0]

lastdf= len(dflist)
test_data = dflist[120:lastdf]

In [36]:

train = train_data

for i in range(len(train_data)):
    

SyntaxError: unexpected EOF while parsing (3737112898.py, line 4)

In [ ]:
sted = df202204.T.sort_values("2022-04")
sted = sted.reset_index()
sted["date"] = sted["level_0"]

del sted["level_0"]
sted = pd.merge(sted, mmnum, on="date")
sted["m+1"] = sted["mnum"]+1
sted = pd.merge(sted, returns, on="mnum")

sted